(* Code automatically generated by 'PreSARAH' *) 
(* Created at 12:06 on 4.4.2014 *) 
 
 
ProcessWrapper = True; 
NameProcess = "2d2nu" 
ExternalFields = {DownQuark, bar[DownQuark], Neutrino, bar[Neutrino]}; 
SumContributionsOperators["2d2nu"] = { 
{OddvvVRR, BOddvvVRR + PSOddvvVRR + PVOddvvVRR + TSOddvvVRR + TVOddvvVRR}, 
{OddvvVLL, BOddvvVLL + PSOddvvVLL + PVOddvvVLL + TSOddvvVLL + TVOddvvVLL}, 
{OddvvVRL, BOddvvVRL + PSOddvvVRL + PVOddvvVRL + TSOddvvVRL + TVOddvvVRL}, 
{OddvvVLR, BOddvvVLR + PSOddvvVLR + PVOddvvVLR + TSOddvvVLR + TVOddvvVLR}}; 

